
name: Dispatch Tests

on:
  workflow_dispatch:
    inputs:
      prTitle:
        description: 'Title of the release PR'    
        required: true
        default: 'chore/<ticket> master to release <year>/<month>'
      tag:
        description: 'Tag for aurora services to trigger release builds'
        required: true

jobs:
  read-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Checkout Repository A
        uses: actions/checkout@v4
        with:
          repository: 'heons/test-semantic-version-up-file'
          token: ${{ secrets.CICD_TOKEN }}
          ref: 'master'
          path: 'repo-a'

      - name: Fetch Tags from Repository A
        run: |
          cd repo-a
          git fetch --tags

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          cd repo-a
          echo "::set-output name=latest_tag::$(git tag | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -t '.' -k 1,1n -k 2,2n -k 3,3n | tail -n 1)"

      - name: Print Latest Tag
        run: |
          echo "The latest tag from Repository A is: ${{ steps.get_latest_tag.outputs.latest_tag }}"

      - name: Replace text
        run: |
          sed -i "s/\"a-api\"\s*=\s*\"[0-9.]*\"/\"aurora-api\" = \"${{ github.event.inputs.tag }}\"/" index.txt
          echo $(cat index.txt)

      - name: Commit
        run: |
          git add .
          git commit -m "version up"
      
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.CICD_TOKEN }}
          destination_branch: "master"
          pr_title: "[Automated] ${{ github.event.inputs.prTitle }}"
          pr_draft: false