
name: Dispatch Tests

on:
  workflow_dispatch:
    inputs:
      env:
        description: Envrionment to release
        required: true
        type: choice
        options:
          - uat
          - prod
      ticket:
        description: 'Ticket number for the release e.g. AURORA-000'
        required: true
      releaseYearMonth:
        description: 'Release year and month e.g. 2024-09'
        required: true
      esIndex:
        description: 'The name of the Elasticsearch index for the release'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  # read-latest-tag:
  #   uses: heons/test-workflow/.github/workflows/create-pr.yml@master
  #   with:
  #     env: ${{ github.event.inputs.env }}
  #     ticket: ${{ github.event.inputs.ticket }}
  #     releaseYearMonth: ${{ github.event.inputs.releaseYearMonth }}
  #     esIndex: ${{ github.event.inputs.esIndex }}
  #   secrets:
  #     PAT: ${{ secrets.CICD_TOKEN }}
  test:
    uses: heons/test-workflow/.github/workflows/validate-pr-title.yml@master
    with:
      env: ${{ github.event.inputs.env }}

