
name: Dispatch Tests

on:
  workflow_dispatch:
    inputs:
      env:
        description: Envrionment to release
        required: true
        type: choice
        options:
          - uat
          - prod
      ticket:
        description: 'Ticket number for the release e.g. AURORA-000'
        required: true
      releaseYearMonth:
        description: 'Release year and month e.g. 2024-09'
        required: true
      esIndex:
        description: 'The name of the Elasticsearch index for the release'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  read-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Checkout Repository A
        uses: actions/checkout@v4
        with:
          repository: 'heons/test-semantic-version-up-file'
          token: ${{ secrets.CICD_TOKEN }}
          ref: 'master'
          path: 'repo-a'

      - name: Fetch Tags from Repository A
        run: |
          cd repo-a
          

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          echo $(pwd)
          cd repo-a
          echo $(pwd)
          git fetch --tags
          VERSION=$(git tag | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -t '.' -k 1,1n -k 2,2n -k 3,3n | tail -n 1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          cd ..
          rm -rf repo-a

      - name: Replace text
        run: |
          sed -i "s/\"a-api\"\s*=\s*\"[0-9.]*\"/\"a-api\"           = \"${{ env.VERSION }}\"/" index.txt
          sed -i "s/\"a-interpolation\"\s*=\s*\"[0-9.]*\"/\"a-interpolation\" = \"${{ env.VERSION }}\"/" index.txt
          sed -i "s/elasticsearch_index_name\s*=\s*\"aurora[^\n]*\"/elasticsearch_index_name = \"${{ github.event.inputs.esIndex }}\"/" index.txt
          echo $(cat index.txt)

      # - name: Commit
      #   run: |
      #     rm -rf repo-a
      #     git checkout -b feature/automated
      #     git config --global user.email "dev@example.com"
      #     git config --global user.name "automated"
      #     git add index.txt
      #     echo $(git status -s)
      #     git commit -m "version up"
      #     echo $(git status -s)
      #     git push origin feature/automated
      
      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CICD_TOKEN }}
          title: "[Automated] chore/${{ github.event.inputs.ticket }} aurora release ${{ github.event.inputs.env }} ${{ github.event.inputs.releaseYearMonth }}"
          body: 'This PR was automatically created by GitHub Actions.'
          branch: chore/${{ github.event.inputs.ticket }}_auora_release_${{ github.event.inputs.env }}
          base: master
